
package views;

import java.awt.Color;
import java.util.HashMap;
import models.Customer;
import models.DBManager;
import models.Order;

/**
 *
 * @author Giacomo
 */
public class CustomerHome extends javax.swing.JFrame {

    //Global variable (Customer Object)to pass loggedCustomer to this page from log-in page
    private Customer loggedInCustomer;
    /**
     * Creates new form CustomerHome
     */
    
    // added Customer to the imput paramenter to initialised the global variable 'loggedInCustomer' 
    public CustomerHome(Customer customer) {       
        loggedInCustomer = customer;//global variable initialisation 
        //it set the background colour at the jframe page
        getContentPane().setBackground(Color.CYAN); 
        initComponents();
        //change the lbl greating text when the homePage is opened         
        lblGreating.setText(loggedInCustomer.displayGreeting());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBrowseProducts = new javax.swing.JButton();
        btnViewMyOrders = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblGreating = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnBrowseProducts.setBackground(new java.awt.Color(0, 102, 153));
        btnBrowseProducts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBrowseProducts.setText("BROWSE PRODUCTS");
        btnBrowseProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowseProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseProductsActionPerformed(evt);
            }
        });

        btnViewMyOrders.setBackground(new java.awt.Color(0, 102, 153));
        btnViewMyOrders.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewMyOrders.setText("VIEW MY ORDERS");
        btnViewMyOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewMyOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMyOrdersActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 51, 51));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblGreating.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGreating.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGreating.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGreating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBrowseProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(btnViewMyOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGreating, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrowseProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewMyOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        //it log out from the Customer's homepage going back to the main menu
        MainMenu mainMenu = new MainMenu();
        this.dispose();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBrowseProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseProductsActionPerformed
        
        loggedInCustomer.setIsRegistered(true);

        //insert current order too
        Order currentOrder = new Order();
        //connect customerHome to ShoppingPage By the button
        ShoppingPage shoppingPage = new ShoppingPage(loggedInCustomer, currentOrder);
        this.dispose();
        shoppingPage.setVisible(true);
    }//GEN-LAST:event_btnBrowseProductsActionPerformed

    private void btnViewMyOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMyOrdersActionPerformed
        // to display the CustomerPreviousOrder window customer order data from the database        
        HashMap<String, Customer> customers = new HashMap();//the customers hashmap allows to display the customers orders 
        customers.put(loggedInCustomer.getUsername(), loggedInCustomer);
        
        DBManager db = new DBManager();
        customers = db.loadCustomerOrders(customers);
         
        loggedInCustomer = customers.get(loggedInCustomer.getUsername());
                
        
        CustomerPreviousOrders customerPreviousOrders = new CustomerPreviousOrders(loggedInCustomer);
        this.dispose();
        customerPreviousOrders.setVisible(true);
    }//GEN-LAST:event_btnViewMyOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CustomerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseProducts;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnViewMyOrders;
    private javax.swing.JLabel lblGreating;
    // End of variables declaration//GEN-END:variables
}
