/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import models.Clothing;
import models.DBManager;
import models.Footwear;
import models.Product;
import models.Staff;

/**
 *
 * @author Giacomo
 */
public class EditProduct extends javax.swing.JFrame {
    
    private Staff loggedInStaff;
    private Product productToEdit;

    /**
     * Creates new form EditProduct
     */
    //into the editProduct constructor oare added the object that will be used in;
    //staff logged and oggected selected
    public EditProduct(Staff staff, Product product) {
        loggedInStaff = staff;
        productToEdit = product;
        //it set the background colour at the jframe page
        getContentPane().setBackground(Color.CYAN);
        initComponents();
        
        //it allows to diplay the product info within the text fields before being modified
        txtProductId.setText(String.valueOf(productToEdit.getProductId()));
        txtProductName.setText(productToEdit.getProductName());
        txtProductPrice.setText(String.valueOf(productToEdit.getPrice()));
        txtStockLevel.setText(String.valueOf(productToEdit.getStockLevel()));
        
        //the if statement will chech the product's typology (Clothing or Footwear)
        //by inserting, as hardcode, one of the two product's typologies into is condition.
        //it will allow to display the correct measurement info the related text field
        if (productToEdit.getClass().getName().equals("models.Clothing"))
        {
            lblExtraAttribute.setText("measurement:");
            
            Clothing clothing = (Clothing)productToEdit;
            txtExtraAttribute.setText(String.valueOf(clothing.getMeasurement()));
        }
        else
        {
            lblExtraAttribute.setText("size:");
            Footwear footwear = (Footwear)productToEdit;
            txtExtraAttribute.setText(String.valueOf(footwear.getSize()));            
        }
        
        txtProductId.setEnabled(false);//it disables theproduct ID text field avoiding its modification to garantee the correct work of product uptdate
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblStockLevel = new javax.swing.JLabel();
        lblExtraAttribute = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtProductPrice = new javax.swing.JTextField();
        txtStockLevel = new javax.swing.JTextField();
        txtExtraAttribute = new javax.swing.JTextField();
        lblErrorMessage = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnReturnToProductSelected = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("EDIT PRODUCT DETAILS");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId.setText("ID:");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Name:");

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setText("Price: £");

        lblStockLevel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStockLevel.setText("Stock Level: ");

        lblExtraAttribute.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExtraAttribute.setText("Extra Attribute:");

        txtProductId.setBackground(new java.awt.Color(0, 204, 204));
        txtProductId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtProductName.setBackground(new java.awt.Color(0, 204, 204));
        txtProductName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtProductPrice.setBackground(new java.awt.Color(0, 204, 204));
        txtProductPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtStockLevel.setBackground(new java.awt.Color(0, 204, 204));
        txtStockLevel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtExtraAttribute.setBackground(new java.awt.Color(0, 204, 204));
        txtExtraAttribute.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblErrorMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorMessage.setForeground(java.awt.Color.black);
        lblErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorMessage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnSubmit.setBackground(new java.awt.Color(0, 153, 102));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReturnToProductSelected.setBackground(new java.awt.Color(0, 102, 153));
        btnReturnToProductSelected.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReturnToProductSelected.setText("Rerturn to Product Selected");
        btnReturnToProductSelected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnToProductSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToProductSelectedActionPerformed(evt);
            }
        });

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrice)
                            .addComponent(lblExtraAttribute)
                            .addComponent(lblName)
                            .addComponent(lblId)
                            .addComponent(lblStockLevel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStockLevel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 95, Short.MAX_VALUE))
                            .addComponent(txtProductName)
                            .addComponent(txtProductPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtExtraAttribute, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReturnToProductSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStockLevel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExtraAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtraAttribute))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnReturnToProductSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnToProductSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToProductSelectedActionPerformed
        //it will allow to display the ModifProduct Page once the button is clicked.
        ModifyProduct modifyProduct = new ModifyProduct(loggedInStaff);
        this.dispose();
        modifyProduct.setVisible(true);
    }//GEN-LAST:event_btnReturnToProductSelectedActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        //here  it will changed all the values into string and displayed and error message
        //if some fiend will be leve empty.
        String productId = txtProductId.getText();
        String productName = txtProductName.getText();
        String productPrice = txtProductPrice.getText();
        String stockLevel = txtStockLevel.getText();
        String extraAttribute = txtExtraAttribute.getText();
        
        if (productId.equals("") || productName.equals("") || productPrice.equals("") || stockLevel.equals("") || extraAttribute.equals("")) 
        {
            lblErrorMessage.setForeground(Color.red);
            lblErrorMessage.setText("Please, fill all the fields");
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/error.png")));
        }
        else
        {
            //the error detection will chech if are inserted the correct data into the relate fields
            //otherwise will be displayed a error message
            try
            {
                int productIdInt = Integer.parseInt(productId);
                double productPriceDouble = Double.parseDouble(productPrice);
                int stockLevelInt = Integer.parseInt(stockLevel);

                //the if statement will chech if the products are cloths or a shoes
                if (productToEdit.getClass().getName().equals("models.Clothing")) 
                {
                    String measurement = extraAttribute;
                    //(int productIdIn, String productNameIn, double priceIn, int StockLevelIn, String measurementIn)
                    Clothing clothing = new Clothing(productIdInt, productName, productPriceDouble, stockLevelInt, measurement);
                    //it joins DBNanager to the button edit to insert the modified clothing value
                    DBManager db = new DBManager();
                    db.editProduct(clothing);
                    
                }
                else
                {
                    int size = Integer.parseInt(extraAttribute);
                    //(int productIdIn, String productNameIn, double priceIn, int StockLevelIn, int sizeIn)
                    Footwear footwear = new Footwear(productIdInt, productName, productPriceDouble, stockLevelInt, size);
                    //it joins DBNanager to the button edit to insert the modified footwear value
                    DBManager db = new DBManager();
                    db.editProduct(footwear);
                }
                
                lblErrorMessage.setForeground(Color.BLACK);
                lblErrorMessage.setText("Product Update Successfully"); //if  the product is well updated, the system will display this message
                lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/stik.png")));
            }
            catch(Exception ex)
            {
                lblErrorMessage.setForeground(Color.red);
                lblErrorMessage.setText("Please insert valid data.");
                lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/error.png")));
            }
        }
     
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnToProductSelected;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblExtraAttribute;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStockLevel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtExtraAttribute;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtStockLevel;
    // End of variables declaration//GEN-END:variables
}
