/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import models.DBManager;
import models.Product;
import models.Staff;

/**
 *
 * @author Giacomo
 */
public class ModifyProduct extends javax.swing.JFrame {

    //Store the prodoct's info whithin load products in DBManager into the new objet Hashmap 
    private Staff loggedInStaff;
    private HashMap<Integer, Product> products;
    /**
     * Creates new form ModifyProduct
     */
    public ModifyProduct(Staff staff) {
        //it will allows to show  to show products when the page is loaded
        loggedInStaff = staff;       
        DBManager db = new DBManager();
        products = db.loadProducts();
        //it set the background colour at the jframe page
        getContentPane().setBackground(Color.CYAN); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturnStaffHome = new javax.swing.JButton();
        lblEditProduct = new javax.swing.JLabel();
        lblCategories = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProduct = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategories = new javax.swing.JList<>();
        btnEditProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnReturnStaffHome.setBackground(new java.awt.Color(0, 102, 153));
        btnReturnStaffHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReturnStaffHome.setForeground(java.awt.Color.black);
        btnReturnStaffHome.setText("RETURN STAFF HOME");
        btnReturnStaffHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnStaffHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnStaffHomeActionPerformed(evt);
            }
        });

        lblEditProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEditProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditProduct.setText("EDIT PRODUCTS");
        lblEditProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCategories.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCategories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategories.setText("CATEGORIES");

        lblProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProduct.setText("PRODUCT");

        lstProduct.setBackground(new java.awt.Color(0, 204, 204));
        lstProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lstProduct.setForeground(java.awt.Color.black);
        jScrollPane2.setViewportView(lstProduct);

        lstCategories.setBackground(new java.awt.Color(0, 204, 204));
        lstCategories.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lstCategories.setForeground(java.awt.Color.black);
        lstCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Clothing", "Footwear" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCategoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCategories);

        btnEditProduct.setBackground(new java.awt.Color(0, 153, 102));
        btnEditProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditProduct.setText("EDIT PRODUCT");
        btnEditProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductActionPerformed(evt);
            }
        });

        btnDeleteProduct.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteProduct.setText("DELETE PRODUCT");
        btnDeleteProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        lblErrorMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorMessage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReturnStaffHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReturnStaffHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduct)
                    .addComponent(lblCategories))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btnDeleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCategoriesValueChanged
        DefaultListModel productList = new DefaultListModel();

        //The product selected from the user is storend in a strind.
        String selectCategory = lstCategories.getSelectedValue();

        for (Map.Entry<Integer, Product> productEntry : products.entrySet())
        {
            //It is getted the selected product fron the Map.Entry
            Product product = productEntry.getValue();

            //The selected product is compared  with the category to which it belongs
            //to return the element selected into the second list
            //"footwear" and "Clothing" are located into the source package "models"
            if (product.getClass().getName().equals("models." + selectCategory))
            {
                productList.addElement(product);
            }
        }
        //lstProducts is the  second LidstBox "Products" where it will displayed the products held in the categories selected.
        lstProduct.setModel(productList);
    }//GEN-LAST:event_lstCategoriesValueChanged

    private void btnReturnStaffHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnStaffHomeActionPerformed
        //it allows to display the "Staff Home" once the button is clicked. 
        StaffHome staffHome = new StaffHome(loggedInStaff);
        this.dispose();
        staffHome.setVisible(true);
        
    }//GEN-LAST:event_btnReturnStaffHomeActionPerformed

    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        //the if statemnt will be allow do display an error message if no product is selected from the list
        if (lstProduct.getSelectedIndex() ==-1) 
        {
            lblErrorMessage.setForeground(Color.red);
            lblErrorMessage.setText("Select a product from the list");
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/error.png")));
        }
        else
        {
            //if a product is selected, then the next three lines will allow to pass either admin than the selected product to 
            //the edit product page
            //to see the product availability it is need to convert the selected value into an Objcet            
            Object selectProductObject = (Object)lstProduct.getSelectedValue();
            Product selectedProduct = (Product)selectProductObject;
            
            EditProduct editProduct = new EditProduct(loggedInStaff, selectedProduct);
            this.dispose();
            editProduct.setVisible(true);
        }
    }//GEN-LAST:event_btnEditProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // Selecting the productId it will be passible delete all the product raw by clicking this button
        
        if (lstProduct.getSelectedIndex() == -1) 
        {
            lblErrorMessage.setForeground(Color.red);
            //it displays an error messafe if  any product is not selected from the products' list
            lblErrorMessage.setText("Select the product you want to delete");
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/error.png")));
        }
        else
        {
            
            Object selectProductObject = (Object)lstProduct.getSelectedValue();
            Product selectedProduct = (Product)selectProductObject;
            
            //once linked the button to the dbmanager it will selected only the pruductID
            DBManager db = new DBManager(); 
            db.deleteProduct(selectedProduct.getProductId());
            
            //it will remove the product selected by Id from the  hashMap 
            products.remove(selectedProduct.getProductId());
            
            DefaultListModel productList = (DefaultListModel)lstProduct.getModel(); //get a copy of the product list
            productList.remove(lstProduct.getSelectedIndex());//remove the selct product fron the list box
            lstProduct.setModel(productList);//set the list without the animal previusly removed
            
            //displays a message which confirm the action
            lblErrorMessage.setForeground(Color.BLACK);
            lblErrorMessage.setText("Product Successfully Removed");
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/stik.png")));
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ModifyProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnReturnStaffHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblEditProduct;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JList<String> lstCategories;
    private javax.swing.JList<String> lstProduct;
    // End of variables declaration//GEN-END:variables
}
