/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import models.Customer;
import models.DBManager;
import models.Order;
import models.OrderLine;
import models.Staff;

/**
 *
 * @author Giacomo
 */
public class StaffPreviosOrderLines extends javax.swing.JFrame {

    //global variables
    private Staff loggedInStaff;
    private int orderId; 
    /**
     * Creates new form StaffPreviosOrderLines
     */
    public StaffPreviosOrderLines(Staff staff, int orderIdIn) {
        loggedInStaff = staff;
        orderId = orderIdIn;
        //it set the background colour at the jframe page
        getContentPane().setBackground(Color.CYAN);
        initComponents();
        
        //calls the customer info from the database which will be displayed in the table using the hashmap
        DBManager db = new DBManager();
        HashMap<String, Customer> customers = db.loadCustomers();
        
        Order order = new Order();
        
        for(Map.Entry<String, Customer> customerEntry : customers.entrySet())
        {
            Customer customer = customerEntry.getValue();
            
            if (customer.getOrders().containsKey(orderId)) 
            {
                order = customer.getOrders().get(orderId);
            }
        }
        
        
        DefaultTableModel basketModel =(DefaultTableModel)tblOrderLines.getModel();
        
        for(Map.Entry<Integer, OrderLine> olEntry : order.getOrderLines().entrySet())
        {
            OrderLine orderLine = olEntry.getValue();
            //display the order's info selectented into the OrderLines Table
            basketModel.addRow(new Object[] {
                orderLine.getProduct().getProductId(),
                orderLine.getProduct().getProductName(),
                "£" + String.format("%.2f", orderLine.getProduct().getPrice()),                
                orderLine.getQuantity(),
                "£" + String.format("%.2f", orderLine.getLineTotal()) 
            } 
            );           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturnToOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderLines = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnReturnToOrder.setBackground(new java.awt.Color(0, 102, 153));
        btnReturnToOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReturnToOrder.setText("RETURN TO ORDERS");
        btnReturnToOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToOrderActionPerformed(evt);
            }
        });

        tblOrderLines.setBackground(new java.awt.Color(0, 204, 204));
        tblOrderLines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductId", "Product", "Price", "Quatity", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblOrderLines);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReturnToOrder)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnReturnToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToOrderActionPerformed
        //displays staffPreviousOrder page
        StaffPreviousOrders previousOrders = new StaffPreviousOrders(loggedInStaff);
        this.dispose(); 
        previousOrders.setVisible(true);
    }//GEN-LAST:event_btnReturnToOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffPreviosOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffPreviosOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffPreviosOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffPreviosOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          //      new CustomerPreviosOrderLines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnToOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrderLines;
    // End of variables declaration//GEN-END:variables
}
